FROM vulnerables/web-dvwa

RUN apt-get update
#RUN apt-get upgrade
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-server

RUN sed -i "s/allow_url_include = Off/allow_url_include = On/g" /etc/php/7.0/apache2/php.ini \
&& sed -i "s/allow_url_include = Off/allow_url_include = On/g" /etc/php/7.0/cli/php.ini \
&& sed -i "s/allow_url_include = 1/allow_url_include = On/g" /etc/php5/apache2/php.ini \
&& sed -i "s/allow_url_include=On/allow_url_include = On/g" /var/www/html/php.ini

RUN sed -i "s/recaptcha_private_key' ] = '/recaptcha_private_key' ] = '6LdK7xITAzzAAL_uw9YXVUOPoIHPZLfw2K1n5NVQ/g" /var/www/html/config/config.inc.php
RUN sed -i "s/recaptcha_public_key' ]  = '/recaptcha_public_key' ]  = '6LdK7xITAAzzAAJQTfL7fu6I-0aPl8KHHieAT_yJg/g" /var/www/html/config/config.inc.php
