---
version: "3.8"
services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: homeAss
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - /home/chnil/persistantDocker/homeAss:/config
    environment:
      - TZ=Europe/Stockholm
    network_mode: host
    restart: unless-stopped
  node-red:
    image: nodered/node-red
    container_name: node-red
    user: 1000
    volumes:
      - /home/chnil/persistantDocker/nodeRed:/data
    environment:
      - TZ=Europe/Stockholm
    ports: 
      - "1880:1880"
    restart: unless-stopped
